# Generated by Django 3.0.6 on 2020-06-30 20:28

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(choices=[('V', 'Veg'), ('N', 'NonVeg')], default=False, max_length=1)),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('snack', 'SNACK'), ('dinner', 'DINNER')], default=False, max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientBasicInfo',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=False, max_length=6)),
                ('age', models.PositiveIntegerField(default=False, null=True)),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('ethnicity', models.CharField(choices=[('indian', 'INDIAN'), ('asian', 'ASIAN'), ('american', 'AMERICAN'), ('latin', 'LATIN'), ('european', 'EUROPEAN'), ('australian', 'AUSTRALIAN'), ('others', 'OTHERS')], default=False, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicalCondition',
            fields=[
                ('patientbasicinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eradicate.PatientBasicInfo')),
                ('diabetes_type', models.CharField(choices=[('I', 'Type1'), ('II', 'Type2')], default=False, max_length=2)),
                ('hba1c_reading', models.CharField(blank=True, max_length=15)),
                ('fasting_reading', models.CharField(blank=True, max_length=15)),
                ('pp_reading', models.CharField(blank=True, max_length=15)),
                ('conditions', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('hBP', 'HYPERTENSION'), ('LBP', 'HYPOTENSION'), ('heart', 'HEARTDISEASE'), ('kidney', 'KIDNEYDISEASE'), ('liver', 'LIVERDISEASE'), ('cancer', 'CANCER'), ('pcod', 'PCOD'), ('pcos', 'PCOS'), ('thyroid', 'THYROID')], default=False, max_length=51, null=True, verbose_name='Medical Conditions')),
                ('medications', models.TextField(blank=True)),
                ('diet_type', models.CharField(choices=[('V', 'Veg'), ('N', 'NonVeg')], default=False, max_length=1)),
                ('current_diet', models.TextField(blank=True)),
                ('fasting', models.CharField(blank=True, max_length=5)),
                ('f_conditions', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('diabetes', 'DIABETES'), ('HBP', 'HYPERTENSION'), ('LBP', 'HYPOTENSION'), ('heart', 'HEARTDISEASE'), ('kidney', 'KIDNEYDISEASE'), ('liver', 'LIVERDISEASE')], default=False, max_length=35, null=True, verbose_name='Family Conditions')),
                ('family_history', models.TextField(blank=True)),
                ('physical_activities', models.TextField(choices=[('daily', 'Daily'), ('4-5', '4-5 times a week'), ('2-3', '2-3 times a week'), ('once', 'Once a week'), ('No', 'No Exercises')], default=False, max_length=15, verbose_name='Exercise Routine')),
            ],
            bases=('eradicate.patientbasicinfo',),
        ),
        migrations.CreateModel(
            name='PatientMenu',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eradicate.PatientBasicInfo')),
                ('breakfast', models.CharField(max_length=250)),
                ('lunch', models.CharField(max_length=250)),
                ('snack', models.CharField(max_length=250)),
                ('dinner', models.CharField(max_length=250)),
            ],
        ),
    ]
